import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import Footer from "@/components/Footer";

export const metadata = { title: "Privacy Policy" };

const LAST_UPDATED = "7 August 2026";

export default function PrivacyPage() {
  return (
    <>
      <main className="min-h-screen bg-white dark:bg-zinc-950 pt-[60px]">
        <div className="max-w-3xl mx-auto px-5 md:px-8 py-14">

          <Link href="/" className="inline-flex items-center gap-2 font-sans text-[10px] tracking-[0.2em] uppercase text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100 transition-colors group mb-10">
            <ArrowLeft size={12} className="group-hover:-translate-x-0.5 transition-transform" />
            Back
          </Link>

          <p className="font-sans text-[9px] tracking-[0.4em] uppercase text-zinc-400 dark:text-zinc-500 font-light mb-3">Legal</p>
          <h1 className="font-serif text-zinc-900 dark:text-zinc-50 leading-none mb-3"
            style={{ fontSize: "clamp(2.4rem, 5vw, 4rem)", fontWeight: 300 }}>
            Privacy Policy.
          </h1>
          <p className="font-sans text-[11px] text-zinc-400 dark:text-zinc-500 font-light mb-12">
            Last updated: {LAST_UPDATED}
          </p>

          <div className="space-y-10 font-sans text-sm text-zinc-600 dark:text-zinc-400 font-light leading-relaxed">

            <section>
              <h2 className="font-sans text-[10px] tracking-[0.3em] uppercase text-zinc-400 dark:text-zinc-500 font-medium mb-4 pb-3 border-b border-zinc-100 dark:border-zinc-800">
                1. Who We Are
              </h2>
              <p>
                Vintage Gallery (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) is a streetwear brand based in Ghana operating at{" "}
                <a href="https://vintagegallery.store" className="text-zinc-900 dark:text-zinc-200 underline underline-offset-2">vintagegallery.store</a>.
                We are committed to protecting your personal information and your right to privacy in accordance with the <strong className="font-medium text-zinc-700 dark:text-zinc-300">Ghana Data Protection Act, 2012 (Act 843)</strong>.
              </p>
              <p className="mt-3">
                For any privacy questions, contact us at{" "}
                <a href="mailto:vintagegallerystore@gmail.com" className="text-zinc-900 dark:text-zinc-200 underline underline-offset-2">
                  vintagegallerystore@gmail.com
                </a>.
              </p>
            </section>

            <section>
              <h2 className="font-sans text-[10px] tracking-[0.3em] uppercase text-zinc-400 dark:text-zinc-500 font-medium mb-4 pb-3 border-b border-zinc-100 dark:border-zinc-800">
                2. Information We Collect
              </h2>
              <p>We collect information you provide directly to us when you:</p>
              <ul className="mt-3 space-y-2 list-disc list-inside marker:text-zinc-300 dark:marker:text-zinc-600">
                <li>Create an account (name, email address, password managed by AWS Cognito)</li>
                <li>Place an order (delivery name, address, phone number)</li>
                <li>Contact us (email content, name)</li>
                <li>Subscribe to updates (email address)</li>
              </ul>
              <p className="mt-4">
                We also collect limited technical information automatically when you visit our website, including your IP address, browser type, device type, pages visited, and referring URL.
              </p>
              <p className="mt-4">
                <strong className="font-medium text-zinc-700 dark:text-zinc-300">Product analytics.</strong> To understand which pieces our customers are interested in, we record when a product page is viewed, roughly how long it stays open, and when an item is added to or removed from a cart or wishlist. These records carry only a random identifier generated by your browser and stored on your device — they are <strong className="font-medium text-zinc-700 dark:text-zinc-300">never linked to your name, email, or account</strong>, and are never shared with or sold to anyone. The analytics run on our own servers; we do not use Google Analytics or advertising pixels. Clearing your browser storage resets the identifier. We delete these records after 180 days.
              </p>
            </section>

            <section>
              <h2 className="font-sans text-[10px] tracking-[0.3em] uppercase text-zinc-400 dark:text-zinc-500 font-medium mb-4 pb-3 border-b border-zinc-100 dark:border-zinc-800">
                3. How We Use Your Information
              </h2>
              <p>We use the information we collect to:</p>
              <ul className="mt-3 space-y-2 list-disc list-inside marker:text-zinc-300 dark:marker:text-zinc-600">
                <li>Process and fulfil your orders</li>
                <li>Send order confirmations, status updates, and delivery notifications via email</li>
                <li>Respond to your inquiries and provide customer support</li>
                <li>Improve and maintain our website and services</li>
                <li>Detect and prevent fraud or abuse</li>
                <li>Send marketing communications (only if you have opted in — you may opt out at any time)</li>
              </ul>
            </section>

            <section>
              <h2 className="font-sans text-[10px] tracking-[0.3em] uppercase text-zinc-400 dark:text-zinc-500 font-medium mb-4 pb-3 border-b border-zinc-100 dark:border-zinc-800">
                4. Payment Processing
              </h2>
              <p>
                All payments are processed by <strong className="font-medium text-zinc-700 dark:text-zinc-300">Paystack</strong>, a PCI-DSS compliant payment provider. We do not store your full MoMo number, bank details, card numbers, or any payment credentials on our servers. We retain only a masked version of your MoMo number (e.g. 024****890) for order records. Please review{" "}
                <a href="https://paystack.com/privacy" target="_blank" rel="noopener noreferrer" className="text-zinc-900 dark:text-zinc-200 underline underline-offset-2">Paystack&apos;s Privacy Policy</a>.
              </p>
            </section>

            <section>
              <h2 className="font-sans text-[10px] tracking-[0.3em] uppercase text-zinc-400 dark:text-zinc-500 font-medium mb-4 pb-3 border-b border-zinc-100 dark:border-zinc-800">
                5. Data Processors & Third Parties
              </h2>
              <p>We do not sell, trade, or rent your personal information. We share data only with the following processors, each bound by their own data protection obligations:</p>
              <ul className="mt-3 space-y-2 list-disc list-inside marker:text-zinc-300 dark:marker:text-zinc-600">
                <li><strong className="font-medium text-zinc-700 dark:text-zinc-300">Delivery partners</strong> — name, phone, and address only, to complete delivery</li>
                <li><strong className="font-medium text-zinc-700 dark:text-zinc-300">Paystack</strong> — for payment processing</li>
                <li><strong className="font-medium text-zinc-700 dark:text-zinc-300">AWS (Amazon Web Services)</strong> — cloud hosting (Lambda, CloudFront, RDS, S3), user authentication (Cognito), and transactional email delivery (SES). Our infrastructure is hosted in the AWS US East (N. Virginia) region, so your data is stored outside Ghana.</li>
                <li><strong className="font-medium text-zinc-700 dark:text-zinc-300">Google (Gmail)</strong> — for transactional order notification emails sent from our business Gmail account</li>
                <li><strong className="font-medium text-zinc-700 dark:text-zinc-300">WeatherAPI.com</strong> — we request current weather for Accra to calculate same-day delivery pricing. No personal data is sent; the request contains only a fixed city location.</li>
              </ul>
              <p className="mt-4">
                We may disclose information if required by law, court order, or government authority in Ghana or any applicable jurisdiction.
              </p>
            </section>

            <section>
              <h2 className="font-sans text-[10px] tracking-[0.3em] uppercase text-zinc-400 dark:text-zinc-500 font-medium mb-4 pb-3 border-b border-zinc-100 dark:border-zinc-800">
                6. Data Retention
              </h2>
              <p>
                We retain your personal information for as long as your account is active or as needed to provide services. Order records are retained for a minimum of <strong className="font-medium text-zinc-700 dark:text-zinc-300">5 years</strong> for financial and legal compliance. You may request deletion of your account and associated data at any time by contacting us — we will action this within 30 days, subject to our legal retention obligations.
              </p>
            </section>

            <section>
              <h2 className="font-sans text-[10px] tracking-[0.3em] uppercase text-zinc-400 dark:text-zinc-500 font-medium mb-4 pb-3 border-b border-zinc-100 dark:border-zinc-800">
                7. Your Rights (Ghana Data Protection Act 2012)
              </h2>
              <p>Under Act 843, you have the right to:</p>
              <ul className="mt-3 space-y-2 list-disc list-inside marker:text-zinc-300 dark:marker:text-zinc-600">
                <li>Know whether we hold personal data about you</li>
                <li>Access the personal data we hold about you</li>
                <li>Request correction of inaccurate or incomplete data</li>
                <li>Request deletion of your account and associated data (subject to legal retention obligations)</li>
                <li>Object to processing of your data for marketing purposes</li>
                <li>Opt out of marketing communications at any time</li>
              </ul>
              <p className="mt-4">
                To exercise any of these rights, email us at{" "}
                <a href="mailto:vintagegallerystore@gmail.com" className="text-zinc-900 dark:text-zinc-200 underline underline-offset-2">
                  vintagegallerystore@gmail.com
                </a>. We will respond within 30 days.
              </p>
            </section>

            <section>
              <h2 className="font-sans text-[10px] tracking-[0.3em] uppercase text-zinc-400 dark:text-zinc-500 font-medium mb-4 pb-3 border-b border-zinc-100 dark:border-zinc-800">
                8. Cookies
              </h2>
              <p>
                We use essential cookies to keep you signed in and to remember your cart, a preference cookie for light/dark mode, and one first-party analytics identifier described in section 2. We do not use third-party advertising or tracking cookies. See our{" "}
                <Link href="/cookies" className="text-zinc-900 dark:text-zinc-200 underline underline-offset-2">Cookies Policy</Link>{" "}
                for a full itemised list.
              </p>
            </section>

            <section>
              <h2 className="font-sans text-[10px] tracking-[0.3em] uppercase text-zinc-400 dark:text-zinc-500 font-medium mb-4 pb-3 border-b border-zinc-100 dark:border-zinc-800">
                9. Security
              </h2>
              <p>
                We use industry-standard measures to protect your information, including HTTPS encryption, secure cloud infrastructure (AWS), JWT-based authentication, and cryptographically random order IDs. No method of transmission over the internet is 100% secure. In the event of a data breach that affects your personal data, we will notify you and the relevant authority within a reasonable timeframe as required by law.
              </p>
            </section>

            <section>
              <h2 className="font-sans text-[10px] tracking-[0.3em] uppercase text-zinc-400 dark:text-zinc-500 font-medium mb-4 pb-3 border-b border-zinc-100 dark:border-zinc-800">
                10. Changes to This Policy
              </h2>
              <p>
                We may update this policy from time to time. If we make significant changes, we will notify you by email <strong className="font-medium text-zinc-700 dark:text-zinc-300">at least 30 days before</strong> the changes take effect. The updated date at the top of this page will always reflect when the policy was last revised. We will not retroactively reduce your rights without your consent.
              </p>
            </section>

            <section>
              <h2 className="font-sans text-[10px] tracking-[0.3em] uppercase text-zinc-400 dark:text-zinc-500 font-medium mb-4 pb-3 border-b border-zinc-100 dark:border-zinc-800">
                11. Contact
              </h2>
              <p>
                For any privacy-related questions or to exercise your rights:<br />
                <a href="mailto:vintagegallerystore@gmail.com" className="text-zinc-900 dark:text-zinc-200 underline underline-offset-2">
                  vintagegallerystore@gmail.com
                </a>
              </p>
            </section>

          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
